### PR TITLE
Responsive page using Bootstrap

### PR DESCRIPTION
**Pull request by bettercallazamat**
## This project has the following features:
1. Project considers responsiveness on each Bootstrap breakpoint
2. Most of the styling and positioning is done using Bootstrap

### CODE REVIEW

**Comment by davitomix** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davitomix** [comment]
## Hi @bettercallazamat. 👨‍🚀  
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****

- [ ] Navbar.
There's an issue with the "lg" size.
It seems the 'before' implementation on the 'ul' breaks.

Screen Shot 2020-03-12 at 8 08 14 PM

This change is required since you must create a copy of the original page as similar as possible to the original and this will make it look professional when it is finished. 😄
 
****

- [ ] Featured Stories.
In 'md', 'lg' and 'xl' sizes there's an issue on the 'featured stories' section.
There's a blank space at the bottom of the section.

Screen Shot 2020-03-12 at 8 13 56 PM

Please fix this, to make your project looks awesome and as similar as possible to the example on which the page is based on this project.
Consider the use of "display" functions available on bootstrap to only show the desired content on certain sizes.
****
### Optional.
These changes are not required by the project but if you decide to implement them they will make your project look fantastic and more detailed.

- [ ] Navbar.
You can implement the ":hover" property on each "a" of the navbar, to change the color when the cursor is over the link.

Screen Shot 2020-03-12 at 8 24 53 PM

- [ ] Main and Footer.
As listed above you could use the same ":hover" property on the title of each article as necessary.

Screen Shot 2020-03-12 at 8 31 05 PM

Screen Shot 2020-03-12 at 8 31 29 PM

Screen Shot 2020-03-12 at 8 31 56 PM

****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. 🔍 ♻️ 
****

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

I wish you the best and see you at the top! 🎖

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
Reviewing pull request.

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @bettercallazamat. 👨‍🚀  
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****

- [x] Navbar.
There's an issue with the "lg" size.
It seems the 'before' implementation on the 'ul' breaks.

Screen Shot 2020-03-12 at 8 08 14 PM

This change is required since you must create a copy of the original page as similar as possible to the original and this will make it look professional when it is finished. 😄
 
****

- [x] Featured Stories.
In 'md', 'lg' and 'xl' sizes there's an issue on the 'featured stories' section.
There's a blank space at the bottom of the section.

Screen Shot 2020-03-12 at 8 13 56 PM

Please fix this, to make your project looks awesome and as similar as possible to the example on which the page is based on this project.
Consider the use of "display" functions available on bootstrap to only show the desired content on certain sizes.
****
### Optional.
These changes are not required by the project but if you decide to implement them they will make your project look fantastic and more detailed.

- [x] Navbar.
You can implement the ":hover" property on each "a" of the navbar, to change the color when the cursor is over the link.

Screen Shot 2020-03-12 at 8 24 53 PM

- [x] Main and Footer.
As listed above you could use the same ":hover" property on the title of each article as necessary.

Screen Shot 2020-03-12 at 8 31 05 PM

Screen Shot 2020-03-12 at 8 31 29 PM

Screen Shot 2020-03-12 at 8 31 56 PM

****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. 🔍 ♻️ 
****

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

I wish you the best and see you at the top! 🎖

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @bettercallazamat, congratulations on building this amazing project, 🙂 very responsive and really a clone. You did great fixing the comments from the previous TSE 👍 . See you at the top ✈️ 
Go ahead and merge to master and submit project completion from 👌 

_Happy coding_ 👨‍💻 
[Daniel Larbi Larbi](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
